package main

import (
	"bufio"
	"bytes"
	"fmt"
	"strings"
	"text/template"
)

const webapp = `

import (
	"fmt"
	"net/http"
	"time"

	"github.com/srinathh/mobilehtml5app/server"
	"golang.org/x/net/context"
)

const greetString = "greetstring"

var srv *server.Server

// Start is called by the native portion of the webapp to start the web server.
// It returns the server root URL (without the trailing slash) and any errors.
func Start() (string, error) {
	srv := server.NewServer()
	srv.HandleFunc(server.GET, "/", index)
	srv.HandleFunc(server.GET, "/:name", hello)
	return srv.Start("127.0.0.1:0", map[string]string{greetString: "Namaste"})
}

// Stop is called by the native portion of the webapp to stop the web server.
func Stop() {
	srv.Stop(time.Millisecond * 100)
}

// These two are autogenerated sample handlers for your webapp to get you started.

func index(_ context.Context, w http.ResponseWriter, r *http.Request) {
	w.Write([]byte("<html><body><div><a href='/Alice'>Alice</a></div><div><a href='/Bob'>Bob</a></div></body></html>"))
}

func hello(c context.Context, w http.ResponseWriter, r *http.Request) {
	name := c.Value("name")
	greetstring := c.Value(greetString)
	fmt.Fprintf(w, "<html><body><div>%s %s!</div><div><a href='/'>Back</a></div></body></html>", greetstring, name)
}
`

func buildDotGradle(b []byte) ([]byte, error) {
	b = bytes.Replace(b, []byte("runProguard false"), []byte("minifyEnabled true"), 1)
	if webview == "xwalk" {
		return append(b, []byte(buildDotGradleTextXwalk)...), nil
	}
	return append(b, []byte(buildDotGradleTextSystem)...), nil
}

const buildDotGradleTextSystem = `
android {
    defaultConfig {
        minSdkVersion 19
    }
}

repositories {
    flatDir{
        dirs 'libs'
    }
}

dependencies {
    compile(name:'backend', ext:'aar')
}

task genGoMobileAAR(type:Exec) {
  workingDir '..'
  commandLine 'gomobile', 'bind', '-o', 'androidapp/libs/backend.aar', '.'
}

preBuild.dependsOn(genGoMobileAAR)
`

const buildDotGradleTextXwalk = `
android {
    defaultConfig {
        minSdkVersion 15
    }
}

repositories {
    maven {
        url 'https://download.01.org/crosswalk/releases/crosswalk/android/maven2'
    }
    flatDir{
        dirs 'libs'
    }
}

dependencies {
    compile 'org.xwalk:xwalk_core_library:14.43.343.17'
    compile(name:'backend', ext:'aar')
}

task genGoMobileAAR(type:Exec) {
  workingDir '..'
  commandLine 'gomobile', 'bind', '-o', 'androidapp/libs/backend.aar', '.'
}

preBuild.dependsOn(genGoMobileAAR)
`

func gradlewrapperDotProperties(b []byte) ([]byte, error) {
	s := bufio.NewScanner(bytes.NewReader(b))
	buf := bytes.Buffer{}
	for s.Scan() {
		txt := s.Text()
		if strings.Index(txt, "distributionUrl") == 0 {
			txt = fmt.Sprintf("distributionUrl=https\\://services.gradle.org/distributions/gradle-%s-all.zip", gradle)
		}
		buf.WriteString(txt + "\n")
	}
	return buf.Bytes(), s.Err()
}

func androidManifestDotXML(b []byte) ([]byte, error) {
	i := bytes.Index(b, []byte("<application"))
	if i < 0 {
		return nil, fmt.Errorf("Could not find <application tag in AndroidManifest.xml")
	}
	buf := bytes.Buffer{}
	buf.Write(b[:i])
	if webview == "xwalk" {
		buf.Write([]byte(androidManifestDotXMLTextXwalk))
	} else {
		buf.Write([]byte(androidManifestDotXMLTextSystem))
	}
	buf.Write(b[i:])
	return buf.Bytes(), nil
}

const androidManifestDotXMLTextXwalk = `
	<!-- Your app might need more permissions depending on functionality your app requires.
	See https://crosswalk-project.org/documentation/embedding_crosswalk.html#Add-code-to-integrate-the-webview -->
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.INTERNET" />
	<uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />

`

const androidManifestDotXMLTextSystem = `
    <uses-permission android:name="android.permission.INTERNET" />

`

func mainDotJava([]byte) ([]byte, error) {
	var tmpl *template.Template
	if webview == "xwalk" {
		tmpl = template.Must(template.New("mainDotJavaText").Parse(mainDotJavaTextXwalk))
	} else {
		tmpl = template.Must(template.New("mainDotJavaText").Parse(mainDotJavaTextSystem))
	}
	params := struct {
		PkgPath string
		PkgName string
		ClsName string
	}{
		PkgPath: pkgPath,
		PkgName: pkgName,
		ClsName: strings.ToUpper(pkgName[:1]) + pkgName[1:],
	}
	buf := bytes.Buffer{}
	if err := tmpl.Execute(&buf, params); err != nil {
		return nil, fmt.Errorf("error writing main.java :%s", err)
	}
	return buf.Bytes(), nil
}

const mainDotJavaTextSystem = `
package {{.PkgPath}};

import android.app.Activity;
import android.os.Bundle;
import android.view.KeyEvent;
import android.webkit.WebSettings;
import android.webkit.WebViewClient;
import android.widget.Toast;

import android.webkit.WebView;
import go.{{.PkgName}}.{{.ClsName}};

public class Main extends Activity {
    private WebView mWebView;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        mWebView = new WebView(this);
		WebSettings webSettings = mWebView.getSettings();
		webSettings.setJavaScriptEnabled(true);
		mWebView.setWebViewClient(new WebViewClient());
        setContentView(mWebView);
    }

	// We start the server on onResume
    @Override
    protected void onResume() {
        super.onResume();
        try {
			mWebView.loadUrl({{.ClsName}}.Start() + "/");
        } catch (Exception e) {
            Toast.makeText(this,"Error:"+e.toString(),Toast.LENGTH_LONG).show();
            e.printStackTrace();
            this.finish();
        }
    }

    // Send a graceful shut down signal to the server. onPause is guaranteed
	// to be called by Android while onStop or onDestroy may not be called.
    @Override
    protected void onPause() {
        super.onPause();
		{{.ClsName}}.Stop();
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
    }

    // We override back key press to close the app rather than pass it to the WebView
    @Override
    public boolean dispatchKeyEvent(KeyEvent event) {
        if(event.getKeyCode() == KeyEvent.KEYCODE_BACK){
            this.finish();
            return true;
        }
        return super.dispatchKeyEvent(event);
    }
}
`
const mainDotJavaTextXwalk = `
package {{.PkgPath}};

import android.app.Activity;
import android.os.Bundle;
import android.view.KeyEvent;
import android.widget.Toast;

import org.xwalk.core.XWalkView;
import go.{{.PkgName}}.{{.ClsName}};

public class Main extends Activity {
    private XWalkView mWebView;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        mWebView = new XWalkView(this, this);
        setContentView(mWebView);
    }

	// We start the server on onResume
    @Override
    protected void onResume() {
        super.onResume();
        if (mWebView != null) {
            mWebView.resumeTimers();
            mWebView.onShow();
        }

        try {
			mWebView.load({{.ClsName}}.Start() + "/", null);
        } catch (Exception e) {
            Toast.makeText(this,"Error:"+e.toString(),Toast.LENGTH_LONG).show();
            e.printStackTrace();
            this.finish();
        }
    }

    // Send a graceful shut down signal to the server. onPause is guaranteed
	// to be called by Android while onStop or onDestroy may not be called.
    @Override
    protected void onPause() {
        super.onPause();
        if (mWebView != null) {
            mWebView.pauseTimers();
            mWebView.onHide();
        }
		{{.ClsName}}.Stop();
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        if (mWebView != null) {
            mWebView.onDestroy();
        }
    }

    // We override back key press to close the app rather than pass it to the XWalkView to give
    // a consistent user experience with how apps behave on Android.
    // Also see https://crosswalk-project.org/jira/browse/XWALK-4816
    @Override
    public boolean dispatchKeyEvent(KeyEvent event) {
        if(event.getKeyCode() == KeyEvent.KEYCODE_BACK){
            this.finish();
            return true;
        }
        return super.dispatchKeyEvent(event);
    }
}
`
const gitignore = `androidapp.iml
.gradle/
.idea/
local.properties
build/
libs/backend.aar
`
